baseURL = "https://blog.rollie.dev/"
languageCode = "en-us"
title = "Rollie Ma - Gopher, Rustacean, Pythonist, Amateur Archaeologist and Corgi Wrangler from Vancouver, BC"
paginate = 5
googleAnalytics = "G-2GKBWFT9P3"
pygmentsUseClasses = true
PygmentsCodeFences = true

[taxonomies]
  tag = "tags"

[permalinks]
  blog = "/:filename/"

[params]
  url = "https://blog.rollie.dev"
  image = "https://rollie.dev/static/images/logos/logo-150x150.png"
  description = "Some random thoughts"
  twitter = "@rolli3ma"

[related]
  threshold = 75
  includeNewer = true
  toLower = false

  [[related.indices]]
    name = "keywords"
    weight = 100

  [[related.indices]]
    name = "tags"
    weight = 100

[markup.goldmark.renderer]
  unsafe= true
